### ISSUE TITLE
Default dispatch in dispatchMulti

### ISSUE THREAD

**Issue by davidnorthetal** [c-blake/cligen#10]
A default "dispatch-route" would be nice in a dispatchMulti case when no dispatch is explicitly named in the arguments.

mb. something like this:
dispatchMulti([foo, default=true], [bar])

**Comment by c-blake** [comment]
I'm not against this as an option, only if the default is specified.  Personally, I prefer with a multi-command like 'git' or 'hg' with no specified subcommand to spit out some kind of summary/indication of subcommands or how to get more help.  So, I would like something like that current behavior to remain the default if no `default` is given.

**Comment by c-blake** [comment]
I should probably also point out that you can basically do what you want now with very little effort by following the example of `test/SemiAutoMulti.nim`.  That uses the regular single `dispatchGen` manually and then drives the multiple dispatch itself in a `proc multi`.  Right now there is a test for `subcmd` that you could reorient to do your default routing.

**Comment by c-blake** [comment]
I think this is rare enough more useful than a help message to not support except by ``test/SemiAutoMulti.nim`` type. Closing.
