### ISSUE TITLE
initFromCL doesn't work with `ref object`

### ISSUE THREAD

**Issue by timotheecour** [c-blake/cligen#118]
```nim
#[
Error: default value is not a tuple or object
    else: error "default value is not a tuple or object"
]#

type Foo = ref object # bug
# type Foo = object # ok
  a1, a2: string
let dfl* = Foo(a1: "junk")
proc main(a: Foo) = discard

when isMainModule:
  import cligen
  var app = initFromCL(dfl)
  app.main()
```

**Comment by c-blake** [comment]
Ok.  Any thoughts on how to make it work?  Does `getTypeImpl` work on such in other contexts?

**Comment by timotheecour** [comment]
untried, but maybe something like:
```nim
process[T](dfl: T) =
  when T is ref | ptr:
    doAssert dfl != nil # could handle this too maybe
    process(dfl[])
  elif T is object:
    sameAsBefore()
```

**Comment by c-blake** [comment]
E.g., it looks like we could do a branch after `of ntyObject`
```Nim
  of ntyRef: ti = ti[0].getTypeImpl[2]
```
That actually makes your example compile and even generates the correct help message!  Could probably do similar for `ptr` and `ptr|ref` to tuple types.  Running fails in the generated setters, though.  We probably just need to set a flag in that branch and elsewhere do the `[]` conditionally upon that flag.  PR welcome if you want to work on it.  I won't have time to do more until at least this weekend.

**Comment by c-blake** [comment]
I could be more careful about checking that the `T` in `ptr|ref T` is an object and this could (maybe?) be generalized to tuples, but the basic usage you were asking for should work.  PRs welcome if you want to dot those i's and cross those t's.

**Comment by timotheecour** [comment]
@c-blake wonderful, thanks!
