### ISSUE TITLE
This repository has no version tags, making it impossible to manage as a dependency.

### ISSUE THREAD

**Issue by jdbernard** [c-blake/cligen#12]
There doesn't seem to be any version tags on the repo, and the version field was last updated two years. 

This is an issue because it means that when this project is a dependency it is impossible to request any version except the latest one. And right now the latest version of this project fails to compile with the current stable version of Nim. So at the moment any project that depends on `cligen` via nimble is broken unless you are running on the Nim `devel` branch.

For example, the following short example is very difficult to compile on nim 0.17.3:

test.nimble
```ini
# Package

version       = "0.1.0"
author        = "Jonathan Bernard"
description   = "Example of difficulty with cligen on Nim 0.17.3"
license       = "MIT"
bin           = @["test"]

# Dependencies

requires "nim >= 0.17.3"

# The following depends transitively on cligen
requires "https://github.com/yglukhov/nim-jwt"
```

test.nim
```nim
echo "Hello World!"
```

Trying to build the project:
```sh
$ nim --version
Nim Compiler Version 0.17.3 (2017-11-15) [Linux: amd64]
Copyright (c) 2006-2017 by Andreas Rumpf

git hash: 25e825df3ad1832c5795eb06369b8fe660a4d02d
active boot switches: -d:release

$ nimble --version
nimble v0.8.8 compiled at 2017-11-15 20:45:37
git hash: f85219872421b47e6b4a8bcbc7c317c9d1304e2d

$ nimble build
Verifying dependencies for test@0.1.0
 Installing https://github.com/yglukhov/nim-jwt@any version
Downloading https://github.com/yglukhov/nim-jwt using git
   Warning: Package 'jwt' has an incorrect structure. It should contain a single directory hierarchy for source files, named 'jwt', but file 'jose.nim' is in a directory named 'private' instead. This will be an error in the future.
      Hint: If 'private' contains source files for building 'jwt', rename it to 'jwt'. Otherwise, prevent its installation by adding `skipDirs = @["private"]` to the .nimble file.
  Verifying dependencies for jwt@0.0.1
 Installing https://github.com/yglukhov/linktools@any version
Downloading https://github.com/yglukhov/linktools using git
  Verifying dependencies for linktools@0.1.0
 Installing cligen@any version
Downloading https://github.com/c-blake/cligen.git using git
   Warning: Package 'cligen' has an incorrect structure. The top level of the package source directory should contain at most one module, named 'cligen.nim', but a file named 'parseopt3.nim' was found. This will be an error in the future.
      Hint: If this is the primary source file in the package, rename it to 'cligen.nim'. If it's a source file required by the main module, or if it is one of several modules exposed by 'cligen', then move it into a 'cligen/' subdirectory. If it's a test file or otherwise not required to build the the package 'cligen.nim', prevent its installation by adding `skipFiles = @["parseopt3.nim"]` to the .nimble file. See https://github.com/nim-lang/nimble#libraries for more info.
  Verifying dependencies for cligen@0.9.4
 Installing cligen@0.9.4
   Success: cligen installed successfully.
 Installing linktools@0.1.0
   Building linktools/linktools using c backend
       Tip: 52 messages have been suppressed, use --verbose to show them.
     Error: Build failed for package: linktools
        ... Details:
        ... Execution failed with exit code 1
        ... Command: "/home/jdb/programs/nim/bin/nim" c --noBabelPath -d:release --path:"/tmp/nimble_25070/githubcom_cblakecligengit"  -o:"/tmp/nimble_25070/githubcom_yglukhovlinktools/linktools" "/tmp/nimble_25070/githubcom_yglukhovlinktools/linktools.nim"
        ... Output: Hint: used config file '/home/jdb/programs/nim/config/nim.cfg' [Conf]
        ... Hint: system [Processing]
        ... Hint: linktools [Processing]
        ... Hint: strutils [Processing]
        ... Hint: parseutils [Processing]
        ... Hint: math [Processing]
        ... Hint: algorithm [Processing]
        ... Hint: osproc [Processing]
        ... Hint: os [Processing]
        ... Hint: times [Processing]
        ... Hint: posix [Processing]
        ... Hint: ospaths [Processing]
        ... Hint: strtabs [Processing]
        ... Hint: hashes [Processing]
        ... Hint: streams [Processing]
        ... Hint: cpuinfo [Processing]
        ... Hint: linux [Processing]
        ... Hint: cligen [Processing]
        ... Hint: macros [Processing]
        ... Hint: tables [Processing]
        ... Hint: parseopt3 [Processing]
        ... /tmp/nimble_25070/githubcom_cblakecligengit/cligen.nim(176, 15) Error: undeclared identifier: 'toNimIdent'
```

**Comment by c-blake** [comment]
Yeah...that ``!`` -> ``toNimIdent`` change was pretty recent and my change morphed a deprecation warning into an error.  Sorry about that.  I don't like to silence deprecation warnings.  I'm happy to put in a ``when declared(toNimIdent)``, though.

**Comment by jdbernard** [comment]
That would fix the immediate problem, thanks!

**Comment by c-blake** [comment]
Done & pushed.  I tested that my test suite worked against a 0.17.2 build.  Don't know about earlier release tags.  I generally don't make backward-breaking changes or use recent Nim features and so haven't worried about version numbers, though I have made a couple recently..not just the one you caught, but also e.g. renaming some identifiers in parseopt3 and that latter one is harder to just "when away".  So, I'll do a version bump now.

**Comment by jdbernard** [comment]
Cool. Could you tag the version (and maybe one or two retroactively) so that Nimble can pull the right commits?

**Comment by c-blake** [comment]
Well, I did one for the most recent bump.  How many do you think we need for nimble to work well?  Just one more at some more or less random backward point in time?  (I almost never use nimble myself, but I definitely see its value for something like yglukhov's universe of packages...)

**Comment by jdbernard** [comment]
I might do one for `v0.9.4` at commit 63a981662ccba1a95dc15ddf8749f2ec045e205e (right before the breaking change) so that packages referencing the last version (v0.9.4) build on nim 0.17.

Thanks for moving so quickly on this!

**Comment by jdbernard** [comment]
And actually, I think most of the packages I'm aware of are referencing the lib by name only, not version, so just the latest tag should be fine.

**Comment by c-blake** [comment]
Done.  You're welcome.  You caught me while I was online with nothing else cooking.

Definitely let me know if you have any other issues.  I don't feel like I have much of a user base..Maybe 3 or 4, really, counting myself.  Maybe there are more stealth happy users out there, though.

**Comment by c-blake** [comment]
Also, unless you have anything more on this issue, I'm going to close it.

**Comment by jdbernard** [comment]
Nope, all good. Thanks again!
