### ISSUE TITLE
cligen breaks on 0.20.2

### ISSUE THREAD

**Issue by genotrance** [c-blake/cligen#136]
```
/home/user/.nimble/pkgs/cligen-0.9.44/cligen.nim(1, 29) Error: invalid pragma: warning[UnusedImport]: off
```

Works on 1.0.x onwards, appreciate a version check to maintain compatibility with 0.20.2.

**Comment by c-blake** [comment]
Sorry.  Works back to 0.19.2 again.  That import warning itself came from cross-compat with gc:arc mode.  An ever more tangled web we weave... ;-)  Do you need me to punch a new release number or can you use cligen#head?

**Comment by genotrance** [comment]
A release will be ideal.

**Comment by c-blake** [comment]
Done.  Let me know if you run into any other problems.
