### ISSUE TITLE
Is it possible to tag 1.2.1 release please?

### ISSUE THREAD

**Issue by cooldome** [c-blake/cligen#164]
Nimble takes latest tagged version of cligen for Nim tests, hence we need a version of cligen with 
https://github.com/c-blake/cligen/commit/9890d72fb0b99b8c1df132df85bda164103a6250 changes in order to fix test failures for https://github.com/nim-lang/Nim/pull/15332

Thanks

**Comment by c-blake** [comment]
Done.  If something is still broken, feel free to submit another PR/ask for another final point release.  I know it's sometimes a pain getting all those packages fixed.  Good luck.
