### ISSUE TITLE
Error: overloaded 'dispatchcount' leads to ambiguous calls

### ISSUE THREAD

**Issue by pb-cdunn** [c-blake/cligen#168]
```
/Users/cdunn/repo/gh/hack/nibsv/nimbleDir/pkgs/cligen-1.2.2/cligen.nim(663, 12) Error: overloaded 'dispatchcount' leads to ambiguous calls
```
That happens when I add a single line:
``diff`
--- src/nib.nim
+++ src/nib.nim
@@ -1,9 +1,11 @@
 from nibpkg/compose import nil
 from nibpkg/refmers import nil
+from nibpkg/mainLookup import nil

 when isMainModule:
   import cligen
   dispatchMulti(
         [compose.compose_variants, cmdName="compose"],
         [refmers.countRefKmers, cmdName="count"],
+        [mainLookup.buildSVIdx, cmdName="count"],
   )
```
Is there a version that we could revert to? We're in the middle of a hackathon.

**Comment by pb-cdunn** [comment]
Never mind. Forgot to change cmdName.

**Comment by pb-cdunn** [comment]
I guess a better help msg would be good though. :smile:

**Comment by c-blake** [comment]
Hmm.  It might be possible for me to put all the dispatchers into a `Table` with some already-used slot protocol for such errors.  "Already used" and "ambiguous call" are preeeeetty similar, though.  So, I'm not sure the value add would be justified.  To the extent it would add value, better messages from the Nim compiler itself seems higher impact.  Good luck on your hackathon. :-)

**Comment by pb-cdunn** [comment]
Good point.
