### ISSUE TITLE
Remove --version and --help from options list

### ISSUE THREAD

**Issue by vitreo12** [c-blake/cligen#189]
Hello, 

Is there a quick way to remove the `--version` and `--help` from the printed options list? I am only able to remove `--help-syntax` by setting `clCfg.helpSyntax = ""`.

Thanks a lot!

**Comment by c-blake** [comment]
Yes.  In the current VC head you can just set any of the 3 builtin options to CLIGEN-NOHELP as per the current RELEASE_NOTES.md

**Comment by vitreo12** [comment]
Thanks a lot! When is this change going to be released in a new version? I'd need it my users to just `nimble install` my package easily, instead of going through git HEADS of the dependencies.

**Comment by c-blake** [comment]
I will probably be releasing a new version in the next few days.  A week at most.

**Comment by vitreo12** [comment]
Sweet! I'll keep an eye on it, keep up the great work :)

**Comment by c-blake** [comment]
Released.  (And thanks.)
