### ISSUE TITLE
Unhelpful compilation error when "short" param name is given as string

### ISSUE THREAD

**Issue by Nindaleth** [c-blake/cligen#191]
This is seen on cligen 1.5.0, nim 1.4.4.

`n` is a string instead of char by mistake (spent some time in Python recently):
```
(...)
import cligen
  dispatchMulti(
    [head, help={
      "lines": "print the first N lines (default = 10)",
      "bytes": "print the first N bytes",
    }, short={
      "lines": "n",
      "bytes": "c",
    }],
  )
```
As long as 100% of all the short aliases are incorrectly double-quoted, instead of single-quoted, I'll get this compilation error that doesn't really help:
```
(...)
/home/black_fox/src/nimutils/nimutils.nim(16, 16) template/generic instantiation of `dispatchMulti` from here
/home/black_fox/src/nimutils/nimutils.nim(17, 6) template/generic instantiation of `dispatchMultiGen` from here
/home/black_fox/.nimble/pkgs/cligen-1.5.0/cligen.nim(199, 58) Error: node lacks field: intVal
```

After switching even one short name to the properly single-quoted form, the compilation error clears up immediately for the remaining incorrect entries:
```
(...)
/home/black_fox/src/nimutils/nimutils.nim(16, 16) template/generic instantiation of `dispatchMulti` from here
/home/black_fox/src/nimutils/nimutils.nim(17, 6) template/generic instantiation of `dispatchMultiGen` from here
/home/black_fox/src/nimutils/nimutils.nim(22, 14) Error: type mismatch: got <(string, string)> but expected '(string, char)'
```

Is there a way the compilation error for the corner case could be improved?

**Comment by c-blake** [comment]
Let me look into it.  As a matter of clarification, a lot of the time Nim will type a collection initializer like `@[]`, `[]`, or `{}` by its first element.  when you say "switching even one", was it a deeper element or the 1st slot?

**Comment by Nindaleth** [comment]
I've tried with 3 elements, the single correctly char-typed element could be in any position to trigger the better error message.

**Comment by c-blake** [comment]
Gotcha.  I've reproduced over here...Trying what I can to improve errmsg.

**Comment by c-blake** [comment]
Let me know if you think the message is ok.  Thought about maybe putting the proc name in there, but the line number traceback probably isolates that anyway.

**Comment by Nindaleth** [comment]
I think this is a pretty good improvement, it even mentions the offending param name which should make it easy to find (and to differentiate it from an internal error). Thanks a lot for the quick fix!
