### ISSUE TITLE
`parseHelps` fails on a single element

### ISSUE THREAD

**Issue by ZoomRmc** [c-blake/cligen#194]
```nim
import cligen
const Help = { "foo": "foooo" }
proc fun(foo = 1):int =
  result = 1
  
dispatch(fun, help = Help)
```
`cligen-1.5.4/cligen.nim(195, 32) Error: index 1 not in 0 .. 0`

Adding bogus entries for params not present in the proc results in Help being ignored.

Nim: 1.5.1
cligen: 1.5.4

**Comment by c-blake** [comment]
Reproduced.  Temporary workaround is to inline the `{}` into the `dispatch` call, as in
```Nim
dispatch(fun, help = { "foo": "foooo" })
```
in your example.

**Comment by c-blake** [comment]
Actually, this works already - you just need to `import tables` and put a `toTable` after the closing brace `}`.  My thinking here was that it is better to have a typed parameter that is more explicit about de-duplication than the `[(key,val),...]` list.   Sorry for not catching this earlier.  The test program for this is `test/PassValues.nim`.

**Comment by ZoomRmc** [comment]
Please, reopen and assign me to update the docs.

**Comment by c-blake** [comment]
@ZoomRmc will do a PR updating docs { somewhere..anywhere :-) } to re-close this.
