### ISSUE TITLE
[BUG] ./app myMandatory:3 => Bad value: "myMandatory:3" for option "non-option 0 (myMandatory)"; expecting int

### ISSUE THREAD

**Issue by timotheecour** [c-blake/cligen#20]
- [ ] mandatory arguments seem not working:

```
proc foobar(myMandatory: int): int =
  ##Some API call
  echo (myMandatory)
  result = 0
```

```
./app myMandatory:3
Bad value: "myMandatory:3" for option "non-option 0 (myMandatory)"; expecting int
Usage:
  foobar [optional-params] {myMandatory:int}
Some API call
  Options(opt-arg sep :|=|spc):
  --help, -?      print this help message
```

- [ ] shouldn't we also support `myMandatory=3` for sake of consistency?

**Comment by c-blake** [comment]
Well, when I wrote that part I was thinking of mandatory command parameters as more like positional function parameters, rather than named parameters.  You can kind of see that from the generated help messages.  I suppose Nim itself lets you go ahead and call ``foobar(myMandatory=3)``, though, and I agree that's more user-friendly.  I will have to look into how to do it.  Happy for any PRs you feel like digging into.

**Comment by timotheecour** [comment]
I see; wasn't clear from docs (an example showing `./app 3` would've helped).

how about making `myMandatory` instead a regular flag, but giving an error when not set by user?
* would follow principle of least surprise
* leads to easier to remember cmd lines
* most important: leads to more robust cmd lines, eg in case API changes by adding / shuffling arguments, it'll give an error instead of silently accepting something wrong

for presentation:
```
Usage:
  foobar [params]
Some API call
  Options(arg sep :|=|spc):
  --help, -?      print this help message
  -myMandatory =, --myMandatory =  int     (required)      set myMandatory
```
or
```
Usage:
  foobar  [required-params] [optional-params]
Some API call
Required(req-arg sep :|=|spc):
  -myMandatory =, --myMandatory =  int     set myMandatory
Options(opt-arg sep :|=|spc):
  --help, -?      print this help message
```

**Comment by c-blake** [comment]
You don't need to add more arguments in favor of this new feature.  I already agreed this is better than the status quo which is less a bug than less than ideal behavior.  I just have to look into it, check corner cases/logic, etc.

**Comment by c-blake** [comment]
I looked it over and I think it would be pretty easy to accept mandatory parameters as option-keyed inputs (as in ``./app --myMandatory=3``) and just keep a record of mention by the user and print an error if the user skips any.  That seems nicer.  It's probably fine to allow them to have short option keys, too, ``-m`` in your example.

The most natural usage/help for this, though, at least IMO, would be your ``"(required)"`` form above.  To do that, though, the ``argHelp`` template for a given type/user-type needs to distinguish between a real default value in ``defVal`` and the mandatory case.  I guess the ``defVal`` parameter to ``argHelp`` could also be a pointer type that could be ``nil`` if the parameter is mandatory.  Or ``argHelp`` could maybe grow an extra argument.  I don't think we want a separate template for mandatory parameters of the same type.

Either way, this feature like https://github.com/c-blake/cligen/issues/16 and https://github.com/c-blake/cligen/issues/17 is probably a breaking change for any existing cligen users doing their own ``argParse/argHelp`` (this one on the ``argHelp`` side, the other two on the ``argParse`` side).  So, similarly, we want to get it right.

**Comment by timotheecour** [comment]
happy to try out whatever you come up with on a separate branch (so we can discuss it more concretely before pushing to master)

**Comment by c-blake** [comment]
I decided a pre-breaking version bump and very LOUD git commit log was enough of a barrier for breaking changes.  Let me know what you think of the new mandatory/required behaviors/interface.
