### ISSUE TITLE
How to bold usage and clCfg.useHdr text from code?

### ISSUE THREAD

**Issue by binaryben** [c-blake/cligen#218]
Hello. I like the gh CLI help formatting and am trying to replicate it using cligen (great package btw!).

I have gotten a significant chunk of the way using the following provided options:

```nim
const ConfigUsage = "ssh-keys $command <section.key> <value>\n\nOPTIONS\n$options"

when isMainModule:
  # ...
  clCfg.hTabCols = @[ clOptKeys, clDescrip ]
  clCfg.useHdr = "${doc}\nUSAGE\n  "
  # ...

  dispatchMulti(
    [ "multi", cmdName=binName, doc=docLine, usage=GlobalUsage ],
    [ configCommand, cmdName="config", doc=ConfigDoc, help=ConfigHelp, usage=ConfigUsage ]
  )
```

[Link to full source code](https://github.com/binaryben/sync-ssh-keys/blob/966f81b527cfc5723e11168393ace5c1732069b2/source/main.nim#L50-L62)

Is there a way to configure the render option from the source code rather than having to rely on the [user specific config file](https://github.com/c-blake/cligen/wiki/Example-Config-File)? I am assuming/hoping there is based on the [presence of clCfg.render](https://github.com/c-blake/cligen/blob/0a074942d2635ed32f7ced7211d1021a9e2b90ad/cligen.nim#L43), but I'm not sure how to make use of that config option to achieve the desired result. I've also tried %(bold) which works in the user config files, but not when set in code.

**Comment by c-blake** [comment]
So, by default I, of course, cannot assume a lot about the environment help is dumped to - even a terminal at all could be wrong.  (Not that you say otherwise - just to be clear.)

I just use the user config myself, but this worked for me:
```Nim
proc foo =
  ## hey there, *red*
  discard

when isMainModule:
  import cligen, cligen/humanUt, tables
  let r = initRstMdSGR({"singlestar": "RED ; plain"}.toTable())
  proc renderMarkup(m: string): string = r.render(m)
  clCfg.render = renderMarkup
  dispatch foo
```

**Comment by c-blake** [comment]
(I would probably have to look at your code more closely to best evaluate how to integrate various humanUt APIs with it - the above was really just to show an easy way to set `.render` at compile time which seemed the crux of your question.)

**Comment by c-blake** [comment]
But, as per this rST parsing/formatting, I think - you can also probably just use that and do things like `"*COMMANDS*"` and `"*LEARN MORE*"` inside your usage string.

**Comment by c-blake** [comment]
Hmm.  Let me look into that.  Since you are just using a big string constant for global usage anyway, you can definitely just put ESC-[-1-m and ESC-[-m around your capitalized words.  If that is too ugly, you could use `std/strformat` and interpolate some local vars at compile-time to make that less ugly.

**Comment by binaryben** [comment]
Is `ESC-[-1-m` and `ESC-[-m` supposed to be written just like that in the string constants? I tried that and it didn't work. Forgive me, I am new to Nim. I'm using this project to learn it.

**Comment by c-blake** [comment]
It's ok.  I had mean the `chr(27)` escape character like "\e[1mLEARN MORE\e[0m".

**Comment by c-blake** [comment]
Ok.  I am working on a kind of hacked up/pared down version of your code trying things.  Give me a few minutes.  `echo "\e[1mLEARN MORE\e[m here"` does work, though. :-)

**Comment by c-blake** [comment]
So, Nim triple quotes does not seem to interpret the `\e`.  If you do this it works to give you bold faced USAGE:
```Nim
const GlobalUsage = "${doc}\e[1mUSAGE\e[m" & """
```
but only for USAGE.  You could do similar how strings are quoted tricks in your other section headings, do single-quote strings throughout, probably declare some `const bold0, bold1` for on/off, etc.  It might be hard to use strformat on that string since it also has targets for `strutils.%` interpolation as well.

Sorry it took so long - I was struggling to find where I stripped the escape, but I never do.  Nim just never put it in there in the first place!  Oops. :-)

**Comment by c-blake** [comment]
Basically like this:
```Nim

const bon = "\e[1m"
const boff = "\e[m"

const GlobalUsage = "${doc}" & bon & "USAGE" & boff & """
  $command <command> [flags] [args]
""" & bon & "COMMANDS" & boff & """
$subcmds
""" & bon & "FLAGS" & boff & """
  --help      Show help for a command
  --version   Show ssh-keys version
""" & bon & "EXAMPLES" & boff & """
  λ $command install
  λ $command add --user=binaryben
  λ $command sync
""" & bon & "LEARN MORE" & boff & """
  Use '$command help <command>' for more information about a command
  Read the docs at https://github.com/binaryben/sync-ssh-keys
""" & bon & "FEEDBACK" & boff & """
  Open an issue at https://bnry.be/ssk-issues
  Request help at https://bnry.be/ssk-help
  Submit feature requests at https://bnry.be/ssk-idea"""
```
but (I think) you could also just use structured comments and teach users how to config cligen.  Then if they want RED instead of bold they can do that, etc.

**Comment by binaryben** [comment]
Thanks @c-blake, got pretty much to what you have in your last comment - just [without the const definitions](https://github.com/binaryben/sync-ssh-keys/commit/a4f3da3685fdfa537fd8fa1522b0541418b7383d).

> but (I think) you could also just use structured comments and teach users how to config cligen. Then if they want RED instead of bold they can do that, etc.

Definitely something I will consider, but will be a stretch goal for now 😄

**Comment by binaryben** [comment]
> Sorry it took so long

Also I hope this is a joke. I don't think I've ever seen an issue on a FOSS project resolved so fast 😂👍🏼

**Comment by c-blake** [comment]
The definitions are more for your "if some user asks to turn it off" or just to look "less ugly" if that is even true.  They could (probably) be `let` with `isatty`-type checking or something, too, but the string may need to be a compile time constant.

Glad you appreciate the fast service!  No patch/PR/release even necessary here. :-)

**Comment by binaryben** [comment]
Ah that is useful information, never knew there was a way to type in a literal escape character. I'll have to look into how to do it in VSCodium. I think I will leave it for this project because it's possible I will make use of `isatty` or similar eventually, but I appreciate the new knowledge
