### ISSUE TITLE
How do I auto-display the help if no arguments are passed?

### ISSUE THREAD

**Issue by kaushalmodi** [c-blake/cligen#27]
Is there a way to use `cligen` and have the compiled binary automatically show the output of `--help` if no switches are passed? i.e. make `./compiled_binary` behave the same as `./compiled_binary --help`?

**Comment by c-blake** [comment]
Options are supposed to be _optional_. ;-)  If you are wrapping a valid ``proc`` with all defaulted parameters that can be invoke correctly as ``foo()`` then ``./foo`` should also work with no arguments.  So, I think you'll probably agree the defaults are right here.  Conceptually, it sounds like you may have one or more mandatory parameters.

That said, you can do this use ``dispatchGen`` and call the generated dispatcher yourself.  E.g.,:
```Nim
proc foo(a=0, b=5.0) = discard

import cligen, os
dispatchGen(foo)
quit(dispatch_foo(if paramCount() > 0: commandLineParams() else: @[ "--help" ]))
```

**Comment by kaushalmodi** [comment]
> Conceptually, it sounds like you may have one or more mandatory parameters.

Right.. am trying to figure out how to make them optional.. having no luck.. 

I now have:

```
proc nistow*(version=false, simulate=false, verbose=false, force=false, app: string, dest: string) =
```

But I want to make `nistow -v` work and not have cligen throw this error:

```
Missing these required parameters:
  app
  dest
Run command with -h for more details.
```

**Comment by c-blake** [comment]
Well, you have a call with required string params ``app`` and ``dest``, right?  It looks like you are defaulting ``dest`` to ``getHomeDir()`` (in the current git-available version), and you want to error out if ``app`` is not provided.  So, what am I missing?  Did you want a full help message with missing mandatory parameters?  I kinda figured those were most likely typos/misspellings of things/etc and the short message would be ok in this context.

**Comment by c-blake** [comment]
Hmm.  Even that may not be enough to block the missing mandatory error out.  You may have to default those mandatory strings to something like "REQUIRED" yourself and check them in a wrapper proc.

**Comment by c-blake** [comment]
There may be a useful new feature request embedded in this question, though..A kind of "standalone option" which if given means none of the mandatory parameters are actually mandatory (i.e., if one of those is present then the dispatcher acts as if every mandatory parameter had been in ``ImplicitDefault``).

**Comment by kaushalmodi** [comment]
@c-blake 

Thanks for giving your time to this discussion. Please bear with me as I am very much inexperienced in Nim.. And so the dumb questions follow..

> you have a call with required string params app and dest, right?

Thanks. I reiterated with that `proc` signature to finally realize that all arguments are *required*. Being used to a *lisp* flavor, is there a way to mark a `proc` parameter as optional?

> So, what am I missing? Did you want a full help message with missing mandatory parameters? 

As you later realize, I am just expecting the proc to evaluate below and quit, and not care if the mandatory args have values.

```nim
  if version:
    writeVersion()
    quit()
```

FYI, I am working in this branch: https://github.com/kaushalmodi/nistow/tree/use-cligen

> That is not really supported behavior even with dispatchGen

I have a lot of reading to do to understand what dispatchGen actually does.. I see that it is defined in `cligen.nim`. *Also I have yet to learn Nim macros.*

>  You may have to default those mandatory strings to something like "REQUIRED" yourself and check them in a wrapper proc.

Yes, that's what finally worked.. I was confused for a long time as to what makes a switch mandatory vs not. I was trying to default the values of those string switches to `""`, but apparently a string arg not being set is the same as being set to `""` in Nim?

> There may be a useful new feature request embedded in this question, though..A kind of "standalone option" which if given means none of the mandatory parameters are actually mandatory 

That would be great! Thanks!

**Comment by c-blake** [comment]
Ok.  I added that feature.  Check out ``test/ImplicitDefault.nim`` to see how to use.  Basically you just tack on a ``mandatoryOverrides = @["version"]``.  It's starting to get kind of far from the idea that the proc being auto-wrapped is something besides a command, though.  A special invocation mode that overrides everything else is not unheard of for an API call, though.

**Comment by kaushalmodi** [comment]
> Ok. I added that feature.

Wow! Let me try that out. Thanks!

**Comment by c-blake** [comment]
To answer one question/confusion implicit in your longer reply, Nim will just default uninitialized values to _something_, depending on the type (unless you use the ``{.noinit.}`` pragma).  ``cligen`` decides on whether something is optional or mandatory based on an _explicit_ assignment construct being syntactically present in the proc signature (by whether the ``[1].kind == nnkEmpty`` is true).

**Comment by kaushalmodi** [comment]
> by whether the [1].kind == nnkEmpty is true

So that condition is true even when I explicitly set the arg to `""` (empty string)?

**Comment by c-blake** [comment]
No, if you have ``proc yadda(..., blah="", ..)`` that should get an empty string default value and be considered optional.  The node kind won't be nnkEmpty, but some node for a string literal (which happens to be the empty string).

**Comment by kaushalmodi** [comment]
> Basically you just tack on a mandatoryOverrides = @["version"]

Thanks, that works! (https://github.com/kaushalmodi/nistow/commit/e6189aef8e2a1c5de2f0bba17282146cef7763b6).

**Comment by c-blake** [comment]
You're welcome.  I'm not really so happy with ``ImplicitDefault`` and ``mandatoryOverride`` because they actually create command syntax which would be disallowed as a Nim proc invocation.  With a proc invocation, the caller needs to provide non-defaulted parameters.  ``cligen`` generates the call and always provides all params.  So, Nim is happy.  There was kind of a gradual evolution (from ``suppress`` even) of command syntax that is more flexible than the proc call syntax, though I would prefer it not go any further, if possible.

**Comment by kaushalmodi** [comment]
>  With a proc invocation, the caller needs to provide non-defaulted parameters. cligen generates the call and always provides all params. So, Nim is happy. 

Thanks, I am now gradually understanding the role of cligen better.

> There was kind of a gradual evolution (from suppress even) of command syntax that is more flexible than the proc call syntax

I have no idea about `suppress`, but it's alright, I am learning things as needed :) 

---

And here's the last commit (https://github.com/kaushalmodi/nistow/commit/16f4cc90fe3facbbb8cb5bd00a5be9bf6a90859e) where I made the `--help` be passed to the dispatch if user passes no switches.

Just one question with that.. Why is the `quit` needed? I obviously tried to see what happens, and not surprisingly an error:

```
        ... nistow.nim(91, 18) Error: expression 'dispatchnistow(if
        ...   ## "is greater" operator. This is the same as ``y < x``.
        ...   0 < paramCount(): commandLineParams() else: @["--help"],
        ...                "Stow 0.1.0 (Manage your dotfiles easily)", "${prelude}$command $args\L$doc  Options(opt-arg sep :|=|spc):\L$options$sep",
        ...                "", "")' is of type 'int' and has to be discarded; start of expression here: nistow.nim(81, 2)
```

**Comment by c-blake** [comment]
Hey.  I don't know if you are still interested, but I just introduced a better way to handle "--version".  See the new ``test/Version.nim`` program for example usage.  The new way has the parser-dispatcher do all the work _outside_ the API call.  The CLI author provides the name of the long option (e.g. "version" or "Version") and a version string. The API code doesn't need to know anything about ``cligen``.  That is cleaner separation more in keeping with the overall ``cligen`` design.

{ This is more advanced and slightly off topic, but that version string could _almost_ be something "automagic" like ``staticExec "git log -1 | head -n1"`` except currently this fails because Nim evaluates all the macro stuff before the ``staticExec``.  So, for now use a real string like ``"0.5.0"``. }

**Comment by kaushalmodi** [comment]
@c-blake Thanks! It works! https://github.com/kaushalmodi/nistow/commit/db5e38facb2c0c65dda90362ce262795e1c2b22d. 

Though, I tried setting the version to a const and use the const var instead of the string "0.1.0" in that commit, and it printed the identifier as-is i.e. did not evaluate it.

**Comment by c-blake** [comment]
You're welcome.  Yeah.   Just string literals for now.  Identifiers in the macro `$` setting just get their name lifted.  I'll let you know if I figure out a way to get it evaluated..Then things like that fancy ``staticExec`` become possible, or a ``staticRead`` to grab a string out of a file, etc.

**Comment by kaushalmodi** [comment]
Thanks, btw you need to update the module version in cligen.nimble.

**Comment by c-blake** [comment]
Oops.  Thanks.  There are definitely too many little things to remember to do when releasing.  I should script it all.

**Comment by kaushalmodi** [comment]
>  I should script it all.

Create a Nim package for that ;-)

Inspiration: https://github.com/goreleaser/goreleaser
