### ISSUE TITLE
Unable to create library when using cligen

### ISSUE THREAD

**Issue by kdheepak** [c-blake/cligen#37]
```
nim compile -d:Release --app:lib --header src/cli.glm
```

When I run the above I get the following error:

```
Hint: ast [Processing]
Hint: cligen [Processing]
Hint: parseopt3 [Processing]
../../../.nimble/pkgs/cligen-#head/cligen/parseopt3.nim(92, 44) Error: undeclared identifier: 'commandLineParams'
```

**Comment by c-blake** [comment]
Hmm.  Does it work if you patch your local copy of ``cligen/parseopt3.nim`` to have an ``import os`` just after the line with ``proc ERR`` on it?  The truth is that I have never before tried to compile anything with ``--app:lib`` in Nim.

**Comment by kdheepak** [comment]
@dom96 said on [gitter](https://gitter.im/nim-lang/Nim?at=5bb267a8e65a6343366ab231) that "DLLs don't have access to the cmd line args". I think since I'm only using cligen inside the `isMainModule` function, I can get around it by using the following (again suggested by @dom96):

```nim
when isMainModule and appType != "lib":
```

**Comment by c-blake** [comment]
Ok.  You could probably also have provided (inside your ``isMainModule`` part) a ``cmdline=os.commandLineParams()`` argument inside the ``dispatch``.  E.g., ``dispatch(myfunc, cmdline=os.commandLineParams())``, although that may also have failed in ``appType == "lib"`` mode.

It is technically feasible to acquire command line arguments from "outside of ``main()``" by calculating based upon the C ``environ`` variable, but Araq did not seem interested in providing this feature.  See https://github.com/nim-lang/Nim/pull/7297#issuecomment-371180659

Anyway, glad you're back to whatever real work you're doing. :-)

**Comment by kdheepak** [comment]
Thanks for the quick answers @c-blake! Also just want to say that cligen is great!

**Comment by c-blake** [comment]
You're welcome, and I'm glad you like it.  Good luck.
