### ISSUE TITLE
How to dispatch a subcommand using an alias name?

### ISSUE THREAD

**Issue by tim-st** [c-blake/cligen#38]
I tried
```nim
  import cligen

  dispatchMulti(
    [startZimHttpServer, cmdName="server"] # full sig: proc startZimHttpServer*(filename: string, port: uint16 = 8080) = 
  )
```
And when I call `zim` (binary name) it seems to understand that "server" is the alias, but when I call `zim server` it tells me that it wants `zim startZimHttpServer` which then works.

**Comment by tim-st** [comment]
That works good, thanks!

**Comment by c-blake** [comment]
Cool.  Also, it is fixed now in the most recent github commit of cligen.  Will be in next release whenever that is, if you don't just use the most recent github.
