### ISSUE TITLE
Is there a way to suppress GcUnsafe warnings?

### ISSUE THREAD

**Issue by pb-cdunn** [c-blake/cligen#4]
E.g.
```
main.nim(242, 18) template/generic instantiation from here
cligen/cligen.nim(283, 22) Warning: not GC-safe: 'main(:env.MyArgcligenDispatcher294045, ...)' [GcUnsafe]
main.nim(242, 19) Warning: not GC-safe: 'dispatchmain(commandLineParams(), "", "${prelude}$command $args\x0A$doc  Options(opt-arg sep :|=|spc):\x0A$options$sep",
             "", "")' [GcUnsafe]
```
Maybe a pragma could suppress that? I hate to have any warnings in my compilation.

**Comment by c-blake** [comment]
I don't get these warnings myself.  I tend to set ``gc = markAndSweep`` in my ``nim.cfg``, but I wouldn't think that should impact gc-safeness analysis.

**Comment by pb-cdunn** [comment]
Maybe try without markAndSweep, and see what happens? Also, maybe try with `--threads:on`

**Comment by c-blake** [comment]
I tried both independently and together.  No changes for me (meaning I don't see the warning) on my whole test/*.nim set of programs and others I compile.  I generally work with the tip of the devel compiler.

**Comment by c-blake** [comment]
By the way, you probably know you can do nim c --warning[GcUnsafe]:off on the command-line or warning[GcUnsafe]=off in your nim.cfg.  It's obviously not the best idea to suppress the warning for all cases where there might be an issue, but I thought I should mention this in case you were unaware of that option.

**Comment by pb-cdunn** [comment]
I'll try to look for this again soon.

For now, note this warning:

    cligen/cligen.nim(296, 12) Hint: 'posNo' is declared but not used [XDeclaredButNotUsed]

That's with a dispatched procedure with no required args, *viz.*:
```
proc foo(
    n_core=0, 
    output="./fubar",
    min_len=2500,
    stream=false) =
```

**Comment by c-blake** [comment]
Should be fixed.  Thanks for the report - I do hint[XDeclaredButNotUsed]=off in my nim.cfg and never see that stuff.  [ Innocuous in generated code, of course, but admittedly annoying -- that's how that warning got globally turned off by me. :-) ]

**Comment by pb-cdunn** [comment]
I'll assume this was me. In a new program, this message began to appear when I started using a global variable, which makes sense.
