### ISSUE TITLE
How can I configure cligen to expect a mandatory non-option argument?

### ISSUE THREAD

**Issue by kaushalmodi** [c-blake/cligen#40]
I have a single dispatch use case like this:

```nim
when isMainModule:
  import cligen
  dispatch(ntangle
           , version = ("version", "0.1.1"))
```

But I need a mandatory non-option argument for this CLI tool. I expect to run it as: `ntangle FILENAME`.

In future I plan to add more switches so that `ntangle FILENAME --someSwitch` would be a possible command too.

Can I have a mix of both non-option and option (or switch) args?

**Comment by kaushalmodi** [comment]
OK, I think this answers: https://github.com/c-blake/cligen/blob/master/DETAILS.md#optional-positional-command-arguments-more-on-rule-1

But I was looking for an example.

I found this: https://github.com/c-blake/cligen/blob/master/test/SeqInt.nim

But it's not clear why `args` is `seq[int]` (**int**) while the invocation example in the docstring is "invocation "demo --alpha=2 hi ho". I think I need `seq[string]`? *Trying it out ..*

**Comment by kaushalmodi** [comment]
ok! `seq[string]` works!

So in https://github.com/c-blake/cligen/blob/master/test/SeqInt.nim, you should have integers in the invocation example? like *"demo 123 456 --alpha=2"*?

**Comment by c-blake** [comment]
Yeah.  You figured it out.  Sorry.  Those doc-comments are often very out-of-sync with the programs.  In this case if you try to ``nim c test/SeqInt; ./test/SeqInt --alpha=2 hi ho`` it fails trying to convert `"hi"` to an int.

**Comment by c-blake** [comment]
BTW, the `args: seq[string]` will be empty if the user provides no non-option arguments.  So, you will have to check `args.len` and raise your own error message to make it mandatory.

I used to have a non-keyword/option syntax for mandatory positional parameters, but @timotheecour persuaded me to change the syntax.  So, now if you want `cligen` to do the error signaling to users, then the expected usage has to use an option like `ntangle --filename WHATEVER`.

The way to trigger that behavior is to just provide no default value in the proc signature as per `test/Mandatory.nim` or `test/MandatorNoPos.nim`.  The help message has `REQUIRED` show up as a default value.  (You can change `"REQUIRED"` to any other string with the `dispatchGen`/`dispatch` parameter `mandatoryHelp`).

Anyway, I am closing this issue.

**Comment by kaushalmodi** [comment]
>  So, you will have to check args.len and raise your own error message to make it mandatory.

That works. Not a problem.

https://github.com/OrgTangle/ntangle/blob/b37ea5c8e2601d4e118f82188bc422863fd645dc/src/ntangle.nim#L267-L283

**Comment by c-blake** [comment]
Sure.  Looks sensible enough...Catching other exceptions, too, with a nice message and all that.
