### ISSUE TITLE
allow passing context variables

### ISSUE THREAD

**Issue by timotheecour** [c-blake/cligen#50]
## motivation
see use case in https://github.com/c-blake/cligen/issues/48 (difficulty 3)

## proposal

myapp.nim:
```nim
proc main(pass: TCmdLinePass, conf: ConfigRef, query = "", project = "", rebuild = false) = # I want to wrap this by cligen
dispatchGen(main, skip=@[pass, conf])
# generates:
proc dispatchMain(pass: TCmdLinePass, conf: ConfigRef, args: seq[string]) = ... # calls main(pass, conf, ...)

# this (see nimfind.nim) can now use dispatchMain:
proc processCmdLine*(pass: TCmdLinePass, cmd: string; conf: ConfigRef) =
  args = cmdToArgs(cmd) # TODO (out of scope for this discussion)
  dispatchMain(pass, conf, args)
```

## proposal 2 (preferred)

Note: this is very related to https://github.com/c-blake/cligen/issues/30

introduce a new proc in cligen.nim:
```nim
proc dispatchParse[T](params: T, args: seq[string]) =
  # parses cmd line arguments into fields of params
```
(there could be some partial code reuse so that dispatchGen and dispatchParse could reuse some code for the `seq[string]` param conversions)

somehow have an option for dispatchGen to just do parameter conversion given fields of an object, eg:
```nim
type Params = ref object
  query: string
  project: string
  rebuild: bool
proc initParams(): Params = ...
proc main2(pass: TCmdLinePass, conf: ConfigRef, params: Params) = ...

# this (see nimfind.nim) can now use dispatchMain:
proc processCmdLine*(pass: TCmdLinePass, cmd: string; conf: ConfigRef) =
  args = cmdToArgs(cmd) # TODO (out of scope for this discussion)
  var params = initParams()
  dispatchParse(params, args)
  main2(pass, conf, params)
```

**Comment by c-blake** [comment]
This could probably be done more simply by just lifting the generated `parser()` out of the parser-dispatcher scope into the global scope and having users just call `dispatchGen` and then `parseAndDispatchFoo()` or `FooFromSeq()`.  I don't think calling the parser without also dispatching to the wrapped proc is as easy, though I'm not sure you actually need to do that.

**Comment by c-blake** [comment]
Also, I feel like the newly added `mergeParams()` may be a solution here with a little thought.  I was waiting for some feedback on those interfaces before punching a new release version.  You should really take a look at `mergeParams()`.

**Comment by c-blake** [comment]
Also, proposal 1 seems like it mostly exists as the `dispatchGen` parameter I called `suppress`.  You probably just need to default the proc parameters to something instead of the Nim-default-initialization.  I feel like between `suppress` and just using outer scope variables to pass stuff around this is not a real issue, and proposal 2 is mostly a dup of https://github.com/c-blake/cligen/issues/30 which at a minimum needs its own brand new `dispatchGen`.  So, I'm closing this.

**Comment by c-blake** [comment]
(Also, see the new `setByParse` parameter which is also very close to your proposal 2, but without objects/new types).
