### ISSUE TITLE
Show errors for ambigious symbol

### ISSUE THREAD

**Issue by alaviss** [c-blake/cligen#51]
Example:
```nim
import cligen, options

func get() = discard

dispatch get
```

This will fail due to ambiguous symbol `get` provided by both `options` and the current module, and the error message is certainly unhelpful:
```
nimble/pkgs/cligen-0.9.17/cligen.nim(215) dispatchGen
test.nim(5, 10) template/generic instantiation of `dispatch` from here
nimble/pkgs/cligen-0.9.17/cligen.nim(215, 19) Error: node is not a symbol
```

**Comment by c-blake** [comment]
First, I agree it's not a great error message for a common situation.  However, the error message in question is not from me, but from Nim.  It has recently changed to `Error: node lacks field: symbol`.  It's also compile time messaging/erroring out not some run time exception I could catch.  So, I'm not sure I have any control at all over what it says.

**Comment by alaviss** [comment]
You can check the node type beforehand. If it's `nnk{Closed,Open}SymChoice` (it was `nnkClosedSymChoice` in this case), then you can just print out every overload found with a nice error message.

A lazy approach is to use `typed{nkSym}` as the parameter to offload the job to the compiler. The error message would not be nice, but it's understandable.

**Comment by c-blake** [comment]
Ah.  Good suggestions.  Do you know a way at the macro call site to refer (more verbosely, obviously) to a specific `get` overload?  If so, I could also put that in the error message as guidance.

**Comment by c-blake** [comment]
(I mean, of course, the type signature not just the module qualifier...)

**Comment by c-blake** [comment]
I went with the lazier `typed{nkSym}` approach.  I agree it's an ugly error message, but I feel it's a better overall solution for you to submit an issue to Nim to get them to format it more nicely for everyone.  See `test/QualifiedSym.nim`.
