### ISSUE TITLE
help doesn't check keys are valid

### ISSUE THREAD

**Issue by timotheecour** [c-blake/cligen#53]
```
proc main(foo = "myfoo") = discard
dispatch(main, help = {"foo2": "help msg"})
```
this should give compiler error (foo2 instead of foo) but doesn't

(btw, haven't answered yet to your other answers, it's on my TODO list, thanks for the detailed answers so far!)

**Comment by timotheecour** [comment]
(and btw, thanks for this project again, happily helping to convert some projects to cligen, eg https://github.com/genotrance/nimterop/pull/21)

**Comment by c-blake** [comment]
Cool.  Let me know what you think about `setByParse` being a table vs. a `seq[(paramName, unparsedValue)]`.  I am kind of leaning toward the latter with a provided `in`/`contains` operator if Nim can't do `string in seq[(string,T)]` already.

It would be even nicer to go all the way to `seq[(paramName, parsedValueVariant)]`, but I don't think we could use variants and still let CLI authors add their own types via custom `argParse`/`argHelp` definitions.  Though I did my best to do enums/sets/seqs/etc., I'm sure there will be a need for custom types.  Maybe I'm missing something about some kind of "Any" type or some other approach in Nim, though.  Very open to ideas.
