### ISSUE TITLE
cligen += doesn't work with ,SV

### ISSUE THREAD

**Issue by timotheecour** [c-blake/cligen#59]
test case: see D20181130T093940 in https://github.com/timotheecour/vitanim/blob/master/testcases/tests/t0000.nim

**Comment by c-blake** [comment]
You know, this is really more about `+=` not working with `seq[string]`.  It works fine with `seq[int]`.  I think `proc add` in `cligen/argcvt.nim:proc argParse*[T](dst: var seq[T], dfl: seq[T] ...` is failing us.

**Comment by c-blake** [comment]
It was actually `argAggSplit` interacting badly with `argParse(var string)`.  Fixed.  Good catch.  I had never used the two together.  I sort of thought the point of `+=` was `--strs+=foo --strs+=bar` which *did* work. :)

**Comment by timotheecour** [comment]
thanks!

**Comment by c-blake** [comment]
Sure.  Let me know what you think about the new `setByParse` ideas.  I think I've recovered as much imperative/state-driven parsing capability as makes sense.
