### ISSUE TITLE
`a: seq[string]` treamtment not consistent with `a: T` for other non-seq types T

### ISSUE THREAD

**Issue by timotheecour** [c-blake/cligen#61]
test case: see D20181130T094445 in https://github.com/timotheecour/vitanim/blob/master/testcases/tests/t0000.nim

`a: seq[string]` treamtment not consistent with `a: T` for other non-seq types T, in that it becomes a positional arg instead of keyword flag

instead, how about requiring an option (in dispatch) for making a seq become positional?

**Comment by c-blake** [comment]
At least for me, many of my commands that I write (or run!) take some `[paths..]` or similar list of strings as an open-ended positional arguments.  Heck, before command-line flags/options where a "thing", this was sort of the aboriginal argv interface.  So, If there was a proc with a `seq[string]` in there, I didn't want CLI authors to have to learn much "to just use it".  So, I try to auto-detect that.  

The `positional` parameter to `dispatchGen`/`dispatch` overrides that.  Does passing `positional=""` with an empty string to `cligen` make it behave as you want?  I am not sure if I ever tested empty string or nil, but I think that is the way to go, CLI author interface-wise.

**Comment by timotheecour** [comment]
positional="" doesnt' seem to work, but I followed up here: https://github.com/c-blake/cligen/issues/62
