### ISSUE TITLE
need travis + appveyor for CI

### ISSUE THREAD

**Issue by timotheecour** [c-blake/cligen#69]
* need travis + appveyor for CI
* can do similar to https://github.com/citycide/glob/blob/master/.travis.yml
* this should avoid need for "Update generated html." commits such as https://github.com/c-blake/cligen/commit/47640250141d8c397754ffe9ca56264ad049b4b0

**Comment by c-blake** [comment]
I don't think we really need this for `cligen`.  It seems the HTML is not reliably served and maybe should just go away in favor of read the doc comment.

**Comment by timotheecour** [comment]
what prevents regressions, without continuous integration?
the autogenerated docs was a seckndary point

**Comment by c-blake** [comment]
I can't stand the long waits of the main Nim repo CI.  I just run my tests manually.  Right now those tests are all of the "compiles and formats help correctly" variety.  We could use some more behavioral ones, but I still don't see the need for some fully automatic CI.

**Comment by timotheecour** [comment]
> I can't stand the long waits of the main Nim repo CI

CI doesn't have to run prior to every commit push; it can be run (in background...) after each commit push, then you get all the benefits with none of the drawbacks you mention

> I just run my tests manually

on all platforms? (OSX, linux, windows); that's where CI shines; plus, it makes it easy to catch regressions early on (say if upstream nim breaks something, you'll know; eg, if in addition to running after each commit, it runs on a fixed schedule; this could be configured later)

Happy to set it up if you agree (in a way that doesn't run BEFORE each commit but after)

**Comment by timotheecour** [comment]
ok fine, the alternative is multi-repo CI, see https://github.com/nim-lang/Nim/issues/8638
