### ISSUE TITLE
Error in dispatchMulti

### ISSUE THREAD

**Issue by Kentoseth** [c-blake/cligen#7]
> nim --version
> Nim Compiler Version 0.16.0 (2017-01-12) [Linux: amd64]
> Copyright (c) 2006-2017 by Andreas Rumpf

The exact code from the example:
```
proc foo(myMandatory: int, mynums: seq[int], foo=1, verb=false) =
  ##Some API call
proc bar(myHiHo: int, myfloats: seq[float], verb=false) =
  ##Some other API call
when isMainModule:
  import cligen; dispatchMulti([foo], [bar])
```

Compiling:

> nim c foo.nim

Error:

> foo.nim(6, 31) Error: type mismatch: got (array[0..0, proc (myMandatory: int, mynums: seq[int], foo: int, verb: bool){.noSideEffect, gcsafe, locks: 0.}], array[0..0, proc (myHiHo: int, myfloats: seq[float], verb: bool){.noSideEffect, gcsafe, locks: 0.}])
> but expected one of: 
> macro dispatchMulti(cmdName = "?"; procBrackets: varargs[untyped]): untyped

Adjusting code:

```
proc foo(myMandatory: int, mynums: seq[int], foo=1, verb=false) =
  ##Some API call
proc bar(myHiHo: int, myfloats: seq[float], verb=false) =
  ##Some other API call
when isMainModule:
  import cligen; dispatchMulti(foo, bar)
```

Similar error:

> foo.nim(6, 31) Error: type mismatch: got (proc (myMandatory: int, mynums: seq[int], foo: int, verb: bool){.noSideEffect, gcsafe, locks: 0.}, proc (myHiHo: int, myfloats: seq[float], verb: bool){.noSideEffect, gcsafe, locks: 0.})
> but expected one of: 
> macro dispatchMulti(cmdName = "?"; procBrackets: varargs[untyped]): untyped

**Comment by c-blake** [comment]
Good catch.  A recent API change has a new first argument for dispatchMulti.  While I updated the doc comment for the macro, I did not update the README.md.  That's fixed now.

**Comment by Kentoseth** [comment]
Code re-compiled and successful this time around.

Thanks!
