### ISSUE TITLE
invalid multiarg syntax accepted

### ISSUE THREAD

**Issue by timotheecour** [c-blake/cligen#76]
- [ ] i thought the plan was to require `=` for multi arg syntax, but:
```
rnim -d:case11 $nim_D/vitanim/testcases/tests/t0000.nim -f=1 --foo2=1 --foo3,:
@[]
```

- [ ] a delimiter should ALWAYS be required if option starts with `--foo,` EXCEPT if it's just the CLEAR seq `--foo,=`
however this currently doesn't error:
```
rnim -d:case11 $nim_D/vitanim/testcases/tests/t0000.nim -f=1 --foo2=1 --foo3,^=
@[]
```
likewise with `--foo3,+=` and `--foo3,@=`

**Comment by c-blake** [comment]
Yeah. There may be a spot or two where ':' snuck through.  Let me look.
