### ISSUE TITLE
Broken with devel

### ISSUE THREAD

**Issue by genotrance** [c-blake/cligen#84]
cligen is breaking with devel today.

https://travis-ci.org/genotrance/nimterop/jobs/473465269#L395

**Comment by genotrance** [comment]
Looks like this broke your code:

https://github.com/nim-lang/Nim/commit/083129286349ba440018cff1ed20172b675b84fe

**Comment by timotheecour** [comment]
@genotrance PR was merged, can you close if it works for you now?

**Comment by c-blake** [comment]
This works for me.  @timotheecour - thanks for the quick fix-up.  Closing.
