### ISSUE TITLE
Doesn't split comma separated values in some configs

### ISSUE THREAD

**Issue by genotrance** [c-blake/cligen#87]
If you specify `--symOverride=1,2,3` on Linux, it splits it into `@["1", "2", "3"]` but the same code on Windows ends up with `@["1,2,3"]`.

**Comment by genotrance** [comment]
Linux also failed on AppVeyor with this test for some reason. Not sure if it is cligen related but worth investigating.

**Comment by c-blake** [comment]
I don't have a Windows test environment.  For me, on Linux, `./test/AllSeqTypes --s=a,b` yields `s: @["a,b"]` which is the expected/documented behavior.

Splitting CSV/multi-argument in one argv slot should not happen anymore.  I'm not sure how anything even knows to use comma as a split delimiter on whichever environment, really.  I was going to mention that for your last issue as well.
