### ISSUE TITLE
cmdName not applied for error messages

### ISSUE THREAD

**Issue by Nindaleth** [c-blake/cligen#90]
EDIT: version: 0.9.19

I have renamed my `openLog` into `tttlatest` like this:

```nim
import cligen
dispatch(openLog, cmdName = "tttlatest")
```

While it works properly for getting help
```
Usage:
  tttlatest [optional-params]
  (...)
```

calling it with improper input `./exename 3` incorrectly returns 

```
openLog does not expect non-option arguments. Got (...)
```

**Comment by c-blake** [comment]
I think the change I just pushed to my devel should fix your problem.  It did for me.  Let me know if it does not.  If it does, I can punch a new release of ``cligen`` soon.

**Comment by Nindaleth** [comment]
Yup, it works. Thanks for the quick fix!

**Comment by c-blake** [comment]
You're welcome.  That was a really easy one...just grep for the expect.non.option and see the wrong variable being used.  A 1-token fix. :-)
